name: Build and Release Maturin Package

on:
  push:
    branches: ["master"]
  pull_request:
  # Tambahan: otomatis upload ke Release saat membuat tag versi baru
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Python (untuk maturin)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Setup Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 4️⃣ Install maturin
      - name: Install maturin
        run: pip install maturin

      # 5️⃣ Build project
      - name: Build Python bindings
        run: maturin build --release --features python_bindings_feature

      # 6️⃣ Upload hasil build sebagai artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: maturin-wheel-${{ matrix.os }}
          path: target/wheels/*.whl

  release:
    # hanya jalan jika event-nya release (bukan push biasa)
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ Download semua artifact dari job build
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      # 2️⃣ Upload ke GitHub Release
      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
