name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
